[package]
name = "redis_cluster_rs"
version = "0.1.5"
authors = ["Atsushi Koge <atuk721@gmail.com>"]
keywords = ["redis", "cluster", "database"]
description = "Redis cluster driver for Rust."
homepage = "https://github.com/atuk721/redis-cluster-rs"
repository = "https://github.com/atuk721/redis-cluster-rs"
license = "MIT"
readme = "README.md"

edition = "2018"

[dependencies]
crc16 = "0.4"
futures = "0.1"
rand = "0.6"
redis = "0.9"
tokio-executor = "0.1"
log = "0.4"

[dev-dependencies]
lazy_static = "1"
tokio = "0.1"
tokio-timer = "0.2"
env_logger = "0.6"
proptest = "0.9"
